Include qqmlglobal_p.h in tst_qmltyperegistrar.cpp to fix build
Fixes build error from testing for an unknown feature flag, i.e.

tst_qmltyperegistrar.cpp:1439:6: error: division by zero in preprocessor
expression

As it's a private feature, include a private header.

Change-Id: I6112d73ebb738a555c05211d8f6c29a053de7b39
Reviewed-by: Fabian Kosmale <fabian.kosmale@qt.io>
Reviewed-by: Mårten Nordheim <marten.nordheim@qt.io>
(cherry picked from commit dec68b9e75a67270f41fdd68d13f7d1639997413)
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>