Add QQuickItem include
Seems to help with an odd MSVC LTO error:

error C2440: 'static_cast': cannot convert from 'T *' to 'T *'
        with
        [
            T=QObject
        ]
        and
        [
            T=QQuickItem
        ]
qtbase/src/corelib/kernel/qpointer.h(75): note: Types pointed to are
unrelated; conversion requires reinterpret_cast, C-style cast or
parenthesized function-style cast

Task-number: QTBUG-133961
Change-Id: Iee9fd1821aaeec305115b8b860c86ced6df530ab
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>