QQmlDebugTranslationService: work around GCC bug std::variant
Like std::optional, libstdc++'s std::variant may leave space outside of
the active object uninitialized. Then GCC complains.

Amends 4c6fb83b980aaca1e039e43ff0504e1ac0cd3aad, which attempted to
workaround this bug by switching from std::monostate to
std::nullptr_t. It didn't work.

qqmldebugserviceinterfaces.cpp:54:21: error: ‘((QArrayDataPointer<char>*)((char*)&translation + offsetof(QQmlTranslation, QQmlTranslation::m_data.std::variant<std::nullptr_t, QQmlTranslation::QsTrData, QQmlTranslation::QsTrIdData>::<unnamed>.std::__detail::__variant::_Variant_base<std::nullptr_t, QQmlTranslation::QsTrData, QQmlTranslation::QsTrIdData>::<unnamed>.std::__detail::__variant::_Move_assign_base<false, std::nullptr_t, QQmlTranslation::QsTrData, QQmlTranslation::QsTrIdData>::<unnamed>.std::__detail::__variant::_Copy_assign_base<false, std::nullptr_t, QQmlTranslation::QsTrData, QQmlTranslation::QsTrIdData>::<unnamed>.std::__detail::__variant::_Move_ctor_base<false, std::nullptr_t, QQmlTranslation::QsTrData, QQmlTranslation::QsTrIdData>::<unnamed>.std::__detail::__variant::_Copy_ctor_base<false, std::nullptr_t, QQmlTranslation::QsTrData, QQmlTranslation::QsTrIdData>::<unnamed>.std::__detail::__variant::_Variant_storage<false, std::nullptr_t, QQmlTranslation::QsTrData, QQmlTranslation::QsTrIdData>::_M_u)))[2].QArrayDataPointer<char>::d’ may be used uninitialized [-Werror=maybe-uninitialized]

This cannot be our bug. QQmlTranslation has a single, non-trivial member
of type std::variant, so the variant is definitely initialized. If
there's a bug, it's in libstdc++, so make the warning go away.

Pick-to: 6.8
Change-Id: Id599211844d0350d7262fffd7315a20f9d367402
Reviewed-by: Ulf Hermann <ulf.hermann@qt.io>
(cherry picked from commit 6776cd639175b4fe673fd4c7290a4cb60a117321)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>